version: '3.1'
services:
  mysql_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: Venus@18
    volumes:
      - my-db:/var/lib/mysql
  tertiary_verify_app:
    image: tertiary-verify
    ports:
      - 8081:8081
volumes:
  my-db: