# Name of the GitHub Actions workflow
name: Build and deploy WAR app to Azure Web App - tertiary-verify

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

# Jobs to run in the workflow
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up the Java environment with Maven
      - name: Set up Java environment
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      # Build the WAR file using Maven
      - name: Build WAR file
        run: mvn clean install

      # Deploy the WAR file to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tertiary-verify'
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_85514716053D45AD8D140FC28D368A84 }}
          package: target/TertiaryVerifyWebApp-1.0-SNAPSHOT.war
